# Kiran Kumar Reddy Donuru : 002678089 : Intro2Dl : Drill-1 

# # # Question - 1

In [2]:
"""Question-1 : I want you to fill a matrix with values ranging from 0-6 by creating a 7*7 n-d array (matrix)"""

"""I am dynamically reading the values of the dimentions. 
Simple the rows and colums the values will always start from 0-(columnsize -1)"""

#Importing the required packages
import numpy as np

#This function is used to create a skeleton of the matrix with the required size
def create_empty_ndarray(n,m):
    nd_matrix = np.zeros((n,m))
    return nd_matrix

#This function is used to populate the skeliton matrix with the required values
def populate_matrix(r,c):
    matrix_n_n = create_empty_ndarray(r,c)
    #print("Looking at the empty matrix\n", matrix_n_n)
    print("Populating the matrix with the given values of 0-{} \n".format(c-1))
    matrix_n_n += np.arange(c)
    return matrix_n_n


r = int(input("rows? : "))
c = int(input("Columns : "))

result_matrix = populate_matrix(r,c)
print("The required matrix is \n",result_matrix)
# print(" The dimensions are :",result_matrix.ndim)

rows? : 7
Columns : 7
Populating the matrix with the given values of 0-6 

The required matrix is 
 [[0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]
 [0. 1. 2. 3. 4. 5. 6.]]


## Question - 2

In [17]:
"""Patches using lists"""

from numpy.lib import stride_tricks

def image_to_Patches(img,siz):
    rows, colms = img.shape
    res_arr = []

    for i in range(0,colms-siz+1):
        res_arr.append(list(img[0][i:i+siz]))
        
    return np.array(res_arr)

img = np.array([[4, 8, 12, 16, 20,24]])

#Assuming the size as 3
siz = 3

print("Patches for the given image\n",img,"\n is \n", image_to_Patches(img, siz))

Patches for the given image
 [[ 4  8 12 16 20 24]] 
 is 
 [[ 4  8 12]
 [ 8 12 16]
 [12 16 20]
 [16 20 24]]


In [20]:
# Patches using strides

initial_matrix = populate_matrix(1,10)
print(initial_matrix,"\n",
      initial_matrix.shape,"\n",
      initial_matrix.strides,"\n",
      initial_matrix.size,"\n",
     )


#non-overlapping patches of size 3
size = 3
H, W = img.shape # taking height, width of the image
shape = [H // size, W // size] + [size, size] #we are applying broadcasting here?


#(row, col, patch_row, patch_col)
strides = [size * s for s in img.strides] + list(img.strides)

#extract patches
patches = stride_tricks.as_strided(img, shape = shape, strides = strides)

print(img)
print(strides)

Populating the matrix with the given values of 0-9 

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]] 
 (1, 10) 
 (80, 8) 
 10 

[[ 4  8 12 16 20 24]]
[144, 24, 48, 8]


In [12]:
"""Question - 2 : Imagine you have 1-D ndarray A, make a  2-D ndarray for which the first row is [A[0],A[1],A[2]]
and other following rows are shifted by unit of one for example the row in last will be shown as
[A[-3],A[-2],A[-1])"""



"""Assuimg the 1ND Array as an immage which has to be divided into patches  """

"""In deep learning we often need to preprocess inputs into patches. This can mean splitting an image into 
overlapping or non-overlapping 2D patches or splitting a long audio or text input into smaller 
equally sized chunks."""

"""Yes - we can make patch extraction fast and lightweight by leveraging how numpy (or torch, tf, jax, etc) 
stores arrays in memory. Numpy stores arrays 
in contiguous memory. This structure makes reading data from the image array very efficient.
Instead of creating a new patches array, we only need to specify how to view the image as an array of patches.
This is where the concept of strides comes in. You’ll notice that each numpy array has shape, 
strides, and itemsize properties. What do these properties mean?"""


"""Shape = dimension of array. Itemsize = the number of bytes per cell (float32 = 32 bits = 4 bytes).
Strides = the number of bytes required to traverse the contiguous memory block to read the next
element along a given dimension.
Strides = # steps-to-traverse * itemsize.
If we know the output shape of the patch tensor, we can then specify the strides appropriately 
to get the desired patches. In numpy, the stride_tricks module 
provides this functionality. For example, here is how you implement 
non-overlapping patch extraction (e.g. for ViT)."""

"""stride_tricks.as_strided   is a general purpose function for viewing any array. 
By specifying the shape and strides we fully define how to traverse this 
array for viewing. In our case we want to view it as patches - the main trick is to 
figure out the correct strides."""


initial_matrix = populate_matrix(1,3)
print(initial_matrix,"\n",
      initial_matrix.shape,"\n",
      initial_matrix.strides,"\n",
      initial_matrix.size,"\n",
     )




#non-overlapping patches of size 8
size = 3
H, W = img.shape # taking height, width of the image
shape = [H // size, W // size] + [size, size] #we are applying broadcasting here?


#(row, col, patch_row, patch_col)
strides = [size * s for s in img.strides] + list(img.strides)

#extract patches
patches = stride_tricks.as_strided(img, shape = shape, strides = strides)

# print(strides)


Patches for the given image
 [[ 4  8 12 16 20 24]] 
 is 
 [[ 4  8 12]
 [ 8 12 16]
 [12 16 20]
 [16 20 24]]
[144, 24, 48, 8]


In [30]:
"""Question - 2 : Imagine you have 1-D ndarray A, make a  2-D ndarray for which the first row is [A[0],A[1],A[2]]
and other following rows are shifted by unit of one for example the row in last will be shown as
[A[-3],A[-2],A[-1])"""

"""Solving it with using strides concept"""

img = np.array([[4,8,12,16,20,24]])

siz = 3
h, w = img.shape

rows, colms = h//siz, w// siz
colms

2

In [89]:
"""Question - 2 : Imagine you have 1-D ndarray A, make a  2-D ndarray for which the first row is [A[0],A[1],A[2]]
and other following rows are shifted by unit of one for example the row in last will be shown as
[A[-3],A[-2],A[-1])"""


"""Coded this before asking question in the slack before my validations of my understanding"""

""" Assuming I am required to generate a (N+1)Dimention ndarray from a given NDimention ndarray"""

#used to rotate the array by one unit
def rotate_the_array(arr):
    res = np.append(arr[1:],(arr[0]))
    return res


#Using this function to generate a (n+1)darray from the given ndarray
def generate_result_ndarray(n,m):
    
    #Using n+1 because adding the another array which creates N+1 darray
    result_matrix = populate_matrix(n+1,m)
    
    for i in range(1,n+1):
        #rotating one unit of previous array
        result_matrix[i] = rotate_the_array(result_matrix[i-1])
        
    return result_matrix
        
    

r = int(input("rows? : "))
c = int(input("Columns : "))


print("Generating {}-Dimensional ndarray \n".format(siz+1), generate_result_ndarray(r,c))



rows? : 8
Columns : 5
Populating the matrix with the given values of 0-4 

Generating 4-Dimensional ndarray 
 [[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]
 [4. 0. 1. 2. 3.]
 [0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 0.]
 [2. 3. 4. 0. 1.]
 [3. 4. 0. 1. 2.]]


# Question - 3

In [ ]:
"""How can we save time using stochastic gradient compared to standard gradient descent? Do we have a better method?"""



'''In many big data setting (say several million data points), calculating cost or gradient takes very long time, because we need to sum over all data points.
We do NOT need to have exact gradient to reduce the cost in a given iteration. Some approximation of gradient would work OK.
Stochastic gradient decent (SGD) approximate the gradient using only one data point. So, evaluating gradient saves a lot of time compared to summing over all data.
With "reasonable" number of iterations (this number could be couple of thousands, and much less than the number of data points, which may be millions), stochastic gradient decent may get a reasonable good solution.
'''

"""My notation follows Andrew NG's machine learning Coursera course. If you are not familiar with it, you can review the lecture series here.

Let's assume regression on squared loss, the cost function is

𝐽(𝜃)=12𝑚∑𝑖=1𝑚(ℎ𝜃(𝑥(𝑖))−𝑦(𝑖))2

and the gradient is

𝑑𝐽(𝜃)𝑑𝜃=1𝑚∑𝑖=1𝑚(ℎ𝜃(𝑥(𝑖))−𝑦(𝑖))𝑥(𝑖)

for gradient decent (GD), we update the parameter by

𝜃𝑛𝑒𝑤=𝜃𝑜𝑙𝑑−𝛼1𝑚∑𝑖=1𝑚(ℎ𝜃(𝑥(𝑖))−𝑦(𝑖))𝑥(𝑖)

For stochastic gradient decent we get rid of the sum and 1/𝑚 constant, but get the gradient for current data point 𝑥(𝑖),𝑦(𝑖), where comes time saving.

𝜃𝑛𝑒𝑤=𝜃𝑜𝑙𝑑−𝛼⋅(ℎ𝜃(𝑥(𝑖))−𝑦(𝑖))𝑥(𝑖)

Here is why we are saving time:

Suppose we have 1 billion data points.

In GD, in order to update the parameters once, we need to have the (exact) gradient. This requires to sum up these 1 billion data points to perform 1 update.

In SGD, we can think of it as trying to get an approximated gradient instead of exact gradient. The approximation is coming from one data point (or several data points called mini batch). Therefore, in SGD, we can update the parameters very quickly. In addition, if we "loop" over all data (called one epoch), we actually have 1 billion updates.

The trick is that, in SGD you do not need to have 1 billion iterations/updates, but much less iterations/updates, say 1 million, and you will have "good enough" model to use.

I am writing a code to demo the idea. We first solve the linear system by normal equation, then solve it with SGD. Then we compare the results in terms of parameter values and final objective function values. In order to visualize it later, we will have 2 parameters to tune.

    set.seed(0);n_data=1e3;n_feature=2;
    A=matrix(runif(n_data*n_feature),ncol=n_feature)
    b=runif(n_data)
    res1=solve(t(A) %*% A, t(A) %*% b)

    sq_loss<-function(A,b,x){
      e=A %*% x -b
      v=crossprod(e)
      return(v[1])
    }

    sq_loss_gr_approx<-function(A,b,x){
      # note, in GD, we need to sum over all data
      # here i is just one random index sample
      i=sample(1:n_data, 1)
      gr=2*(crossprod(A[i,],x)-b[i])*A[i,]
      return(gr)
    }

    x=runif(n_feature)
    alpha=0.01
    N_iter=300
    loss=rep(0,N_iter)

    for (i in 1:N_iter){
      x=x-alpha*sq_loss_gr_approx(A,b,x)
      loss[i]=sq_loss(A,b,x)
    }
The results:

as.vector(res1)
[1] 0.4368427 0.3991028
x
[1] 0.3580121 0.4782659
Note, although the parameters are not too close, the loss values are 124.1343 and 123.0355 which are very close.

Here is the cost function values over iterations, we can see it can effectively decrease the loss, which illustrates the idea: we can use a subset of data to approximate the gradient and get "good enough" results.


Now let's check the computational efforts between two approaches. In the experiment, we have 1000 data points, using SD, evaluate gradient once needs to sum over them data. BUT in SGD, sq_loss_gr_approx function only sum up 1 data point, and overall we see, the algorithm converges less than 300 iterations (note, not 1000 iterations.) This is the computational"""
